manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  opw_kinematics_geometric_parameters:
    a1: 0.05
    a2: -0.035
    b: 0.000
    c1: 0.457
    c2: 0.440
    c3: 0.420
    c4: 0.080
  opw_kinematics_joint_offsets: [0, 0, deg(-90), 0, 0, deg(180)]
  opw_kinematics_joint_sign_corrections: [1, 1, -1, -1, -1, -1]